### ISSUE TITLE
Inserting entry labels from Sign Bank removed final hold

### ISSUE THREAD

**Issue by geograil** [DCS-LCSR/SignStream3#113]
File: Rachel 65, Utterance 5

I added a final hold to the non-dominant hand of STUDY, and when I went to check the handshapes, I had to add in the primary and variant entry labels to be able to save the gloss. Once I did that and hit Enter, it removed the final hold I had placed there. 

Steps: 

1. Unlocked left-right hand alignments and added final hold to Gloss 2 field. 

![screen shot 2017-01-27 at 2 54 45 pm](https://cloud.githubusercontent.com/assets/19953651/22385585/3d326cb0-e4a1-11e6-8c60-9919ba10535a.png)

2. Opened the Morph-Phon Info box to check handshapes and other information.

![screen shot 2017-01-27 at 2 55 41 pm](https://cloud.githubusercontent.com/assets/19953651/22385597/4e79fbf0-e4a1-11e6-8cf7-fd2852c27af9.png)

3. I tried to hit Enter, but it wouldn't let me since it thought it wasn't in the Sign Bank. I then had to search the Sign Bank for it. Once I found it, I hit the button to "Insert Labels of Primary Entry and Variant"

![screen shot 2017-01-27 at 2 56 05 pm](https://cloud.githubusercontent.com/assets/19953651/22385622/696eddfe-e4a1-11e6-8e21-0aa8bee54309.png)

4. The Morph-Phon Info Box populated those two fields, so I double checked that nothing else changed and hit Enter. 

![screen shot 2017-01-27 at 2 56 22 pm](https://cloud.githubusercontent.com/assets/19953651/22385660/998c60a6-e4a1-11e6-810e-744ec02ffbca.png)

5. The final hold was removed on STUDY.

![screen shot 2017-01-27 at 2 56 35 pm](https://cloud.githubusercontent.com/assets/19953651/22385676/a4893524-e4a1-11e6-8552-f96cb9e31a15.png)

I reproduced it three times in a row doing that exact sequence of steps

**Comment by gregorydimitriadis** [comment]
Reproduced this bug on my end as well - scheduled for next sprint.

Note: This also applies even without the step of entering into the Sign Bank. Meaning, just copy manually the text from 'Entry/Variant' to 'Primary Entry' and press enter out of the Morph-Phon window - same result.

**Comment by gregorydimitriadis** [comment]
For this bug, the issue is on the surface that the final hold (and other associated elements also) get removed when exiting the MorphPhon window of an unlocked gloss. I have fixed that issue for unlocked glosses in this scenario. But more broadly, I also will make some changes to avoid the scenario going forward. 

I have noticed that the locking/unlocking logic does not work exactly as expected. If the gloss gets locked, and one hand has a final hold and the other does not, currently Signstream will ignore this and not match the corresponding/dependent gloss to the selected gloss and whether it has a final hold or not. My change will be so that the locking action fulfills its stated purpose and locks the correspoding/dependent gloss fully to the selected gloss when the locking occurs - meaning, the start/end times will match, the inital/final holds will match, and the onset/offset will match according to the gloss which is selected.

This should make certain what will happen when a lock occurs. And when a gloss is unlocked, the two hands are independent in time, and the MorphPhon window will do nothing to change that. This should avoid any inconsistency between all these actions.

**Comment by geograil** [comment]
Sounds great Greg! I'll definitely let you know if I run into issues with
it once that Sprint is released. Thank you for all the work you do, really!

Boston University, 2018
College of Arts and Sciences | Anthropology - Biological Track with Honors,
B.A.
School of Education | Deaf Studies, B.S.
Minor | Biology

Student Government | Director of Social Affairs


On Tue, Jan 31, 2017 at 11:04 AM, Greg Dimitriadis <notifications@github.com

**Comment by hammondcl** [comment]
This bug is still occurring. I opened the same gloss as before and added in the labels, hit enter, and the final hold was removed. 

That said, it does not happen with glosses that have a final hold on both hands, such as TEST (same utterance - Rachel 65, U5). It only seems to happen with things that have a final hold on only one hand. - Graham

**Comment by gregorydimitriadis** [comment]
I just looked back and realized this may be due to another, separate issue actually. It seems every gloss is loading as locked, regardless of how it was saved. I just looked at the original collection this issue came from and saw the gloss looking like this, despite it supposed to have been unlocked:

![screen shot 2017-02-15 at 14 16 03](https://cloud.githubusercontent.com/assets/847197/22991200/8a79add4-f389-11e6-9832-63a4df5bb108.png)

Is it the same on your end? If so I will re-mark this as a bug to check.

**Comment by geograil** [comment]
It is like that in this utterance. It isn't the case for all glosses though; I have some others with final holds that have unlocked properly.

**Comment by gregorydimitriadis** [comment]
Are there any two-handed glosses which are unlocked in terms of right-left hands? E.g. in this same collection and utterance (Rachel 65, U5) the gloss TEST (in the original file data as I received it) should be like that - but it is displaying as being locked (which is incorrect).

**Comment by geograil** [comment]
When I was coding them, they did appear unlocked. However, after I saved, quit, and re-opened the file, they are all looking like the picture above throughout the file, regardless of whether they have a final hold on one hand or not.

**Comment by aimeeaylward** [comment]
This bug is still happening. We tried again and they were still coming up locked.

**Comment by geograil** [comment]
The final holds are also still dropping, same as before

**Comment by gregorydimitriadis** [comment]
@aimeeaylward @geograil -- this is still occurring after using the patched version I emailed around on Wednesday (2/15) ?

**Comment by geograil** [comment]
Yes, we are using the patched version

**Comment by gregorydimitriadis** [comment]
@aimeeaylward @geograil  I can no longer reproduce this issue - neither the final hold dropping nor the auto-locking. Is it still occurring on your end in this collection or any other?

**Comment by geograil** [comment]
I tested a gloss in Rachel 52, and it did not happen. However, when I rechecked it with this exact gloss in Rachel 65, U 65 for STUDY, I reproduced the final hold drop.

**Comment by gregorydimitriadis** [comment]
Is this occurring with this file in Dropbox, or a separate one? Rachel_2012-02-14_sc65-DAI.ss3

This one says that gloss STUDY is locked, and so appropriately should match left and right hands.

**Comment by geograil** [comment]
Yes, it is occurring in the dropbox file. The gloss looks like this when I open the file: 

![screen shot 2017-04-07 at 2 52 45 pm](https://cloud.githubusercontent.com/assets/19953651/24815088/f3b24a96-1ba1-11e7-8e48-0b6703313af1.png)

After I open the Morph-Phon Info box and add the labels for primary/variant, it appears as such:

![screen shot 2017-04-07 at 2 53 40 pm](https://cloud.githubusercontent.com/assets/19953651/24815120/15f2f3e4-1ba2-11e7-8a18-2e2cdddefcc1.png)

**Comment by gregorydimitriadis** [comment]
So in the database for this collection I'm seeing that this gloss is currently saved as Locked=True, which gets indicated on the GUI with the blue markers. Thus editing hand1 should reflect hand2, which seems to occur. Granted, it should not be locked because only one hand has a final hold whereas the other does not. So I think this gloss (and any others like it which are similar) are just in a bad state - having been unlocked at some previous point, one hand given a final hold, then inadvertently locked and saved in a bad state. For these I recommend deleting the gloss and re-doing it to get it out of the bad state.
