### ISSUE TITLE
Go-to-end-of-utterance button not working - est. 5 hours

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#211]

**Comment by cneidle** [comment]
The "go to end of utterance" button works, in the sense that the green video alignment indicator goes there, but the display fails to show the current frame when that happens.  (This is surely related to the prior bug about not always showing the current frame (#179), but I *thought* that had been fixed.)

Here are two screen shots -- the first after I select "go to end of utterance" from the button in the utterance window; the second after I manually scroll to the end of the utterance:

<img width="1453" alt="screen shot 2018-05-02 at 2 59 52 pm" src="https://user-images.githubusercontent.com/13629122/39543567-9affede4-4e19-11e8-9694-02f92c39f397.png">

<img width="1396" alt="screen shot 2018-05-02 at 3 00 11 pm" src="https://user-images.githubusercontent.com/13629122/39543572-a052f796-4e19-11e8-853f-d22303d7876c.png">

**Comment by gregorydimitriadis** [comment]
@cneidle I can't seem to reproduce this one. Does it only happen sometimes, or for every collection and utterance you try?

**Comment by cneidle** [comment]
It happens VERY regularly— pretty much for every collection and for every utterance
(in which the entire utterance is not in the visible area).

Random example:

Opening up this utterance, clicking on the “go to end of utterance button”.
The green alignment indicator is where it needs to be, but it is out of visible range.
Using the arrow keys to advance by 1, e.g., makes it all visible.

Thanks,
 Carol


Go to end of utterance 




Here it is after using the arrow key:

**Comment by cneidle** [comment]
This is perhaps a related problem.  When using the + button to adjust the endpoint of a selected item, the end frame (+1) should become visible.  This is not happening in file 112, U 85

<img width="1361" alt="screen shot 2018-06-06 at 2 34 51 pm" src="https://user-images.githubusercontent.com/13629122/41058174-19d98d94-6997-11e8-8177-b0a250a997d5.png">

**Comment by cneidle** [comment]
Addendum to previous:  In fact, even when the end frame is initially visible, adding 1 to the end frame causes the field of view to jump back so that it ceases to be visible.

<img width="1112" alt="screen shot 2018-06-06 at 2 37 51 pm" src="https://user-images.githubusercontent.com/13629122/41058255-526cdbde-6997-11e8-9942-36fda44bdfaf.png">


<img width="1113" alt="screen shot 2018-06-06 at 2 37 59 pm" src="https://user-images.githubusercontent.com/13629122/41058267-5a8009d6-6997-11e8-9fd6-6b9541a05d19.png">

**Comment by cneidle** [comment]
Furthermore, "go to end" of object has exactly the same (incorrect) effect as using the +/- buttons to adjust the end frame, with respect to what is visible when that is invoked.

**Comment by cneidle** [comment]
I have also seen several instances of the inverse problem:  where "go to beginning" of an event causes that frame to go from being visible to NOT being visible.  For example:

<img width="972" alt="screen shot 2018-07-05 at 11 04 32 am" src="https://user-images.githubusercontent.com/13629122/42331436-6716d2c0-8043-11e8-8862-b20dc7c9923c.png">

then click on "go to beginning" of selected event

<img width="975" alt="screen shot 2018-07-05 at 11 04 40 am" src="https://user-images.githubusercontent.com/13629122/42331464-71773430-8043-11e8-9241-fdcd207bb7b3.png">

**Comment by cneidle** [comment]
PS to previous comment:  Resetting the start point for that event also causes the relevant frame to cease to be in the visible field.

**Comment by gregorydimitriadis** [comment]
~Fixed in v3.1.1~

**Comment by cneidle** [comment]
This is NOT fixed.

Please reopen, as top priority.

Thanks,
 Carol

**Comment by gregorydimitriadis** [comment]
Sorry - marked the wrong issue.

**Comment by gregorydimitriadis** [comment]
On another attempt, I was able to reproduce this.

**Comment by travisnguyen** [comment]
It looks like this bug has been resolved in version 3.1.2.
