### ISSUE TITLE
Search not working properly

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#368]
Searching for specific values is not working.

<img width="1040" alt="Screen Shot 2020-08-26 at 12 08 47 PM" src="https://user-images.githubusercontent.com/13629122/91328505-0b109180-e795-11ea-8c8d-710d2a20ab7f.png">

<img width="1040" alt="Screen Shot 2020-08-26 at 12 08 58 PM" src="https://user-images.githubusercontent.com/13629122/91328500-0a77fb00-e795-11ea-9ced-62ae1c5c9c4d.png">

**Comment by cneidle** [comment]
This is still a problem, just FYI.

**Comment by gregorydimitriadis** [comment]
Reproduced, with a couple other cases as well.

**Comment by gregorydimitriadis** [comment]
Fixed for next release.

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

Still broken.  Check if it is comparing name with labels (or vice versa)...etc.

Keeping open.

**Comment by gregorydimitriadis** [comment]
Will be fixed in versions:
3.7.0_pre_2021_05_25_1704_16f12c84
4.1.0_pre_2021_05_25_1708_694156a2
