### ISSUE TITLE
Previous utterance incorrectly highlighted as visible in utterance index

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#447]
I am displaying U8.  If I click to go to U7, nothing happens.  The utterance display does not change.
It should jump to the beginning of that utterance.

<img width="1258" alt="Screen Shot 2021-05-14 at 12 07 48 PM" src="https://user-images.githubusercontent.com/13629122/118298191-26e7cf00-b4ad-11eb-9729-51a8a08855a5.png">

Also, I don't know why when I go to a particular utterance, e.g., U5, there is highlighting of the previous utterance, which is not being displayed.

<img width="1239" alt="Screen Shot 2021-05-14 at 12 11 13 PM" src="https://user-images.githubusercontent.com/13629122/118298512-8cd45680-b4ad-11eb-86c1-e38eaa6d498a.png">

**Comment by douglas-motto-at-rutgers** [comment]
Can you post the collection file?

**Comment by douglas-motto-at-rutgers** [comment]
Believe to be an XML problem.

Need to think about how best to deal with all these XML problems.

**Comment by foltik** [comment]
Fixed another issue with utterance index selection that may be related. Needs re-testing with `SignStream3_3.7.0_pre_2021_05_14_1713_f4fd6844`.

**Comment by gregorydimitriadis** [comment]
Cannot reproduce in the version Jack noted.

**Comment by cneidle** [comment]
This issue is partially resolved.  It is now possible to advance to another utterance.
However, the display problem remains.  If I click on U9, it should advance to the beginning of that utterance and should not be displaying the previous utterance.  However, it seems to be doing that, as evidenced by the highlighting:

<img width="794" alt="Screen Shot 2021-05-19 at 11 00 11 AM" src="https://user-images.githubusercontent.com/13629122/118836039-853bf580-b891-11eb-8f63-ae0fe5caf066.png">

This is a systematic problem.

**Comment by foltik** [comment]
Your last screenshot looks like it has U11 selected and displayed, did you click U9 to have nothing change at all?

**Comment by gregorydimitriadis** [comment]
Separate question - in this collection is there any length (of time) between the utterances showing as gray/blue?

**Comment by foltik** [comment]
The previous utterance looks to be only highlighted when it ends at exactly the same time as the current utterance starts. Seems like this should be the expected behavior, as presumably an event could end at the exact end of the previous utterance and be visible at the start of the next.

**Comment by cneidle** [comment]
NO.  This is not the expected, nor the desired, behavior.   Can you fix it so that this case will not cause the previous utterance to be highlighted?    Thank you.

**Comment by cneidle** [comment]
In answer to the question above "Your last screenshot looks like it has U11 selected and displayed, did you click U9 to have nothing change at all?"  The screenshot was not illustrating the case of U9 specifically.  U9 was just chosen as a random example of an utterance number.  There is nothing anomalous shown in the screen shot I provided.  The point is that I am now able to select utterances (so that prior issue has been resolved), but, as discussed subsequently, the display of the previous utterance (which ends at the start frame of the next one) should not be highlighted.

**Comment by cneidle** [comment]
> Separate question - in this collection is there any length (of time) between the utterances showing as gray/blue?

   Answer from Carol:  No.  Jack is correct that the end point of the previous utterance is = the start point of the next one.  But all that is actually displayed is that latter utterance.

This is what you see when you click on U9.

<img width="1439" alt="Screen Shot 2021-05-19 at 1 49 59 PM" src="https://user-images.githubusercontent.com/13629122/118860325-4023bd80-b8a9-11eb-8fea-1f33c6a6f161.png">

This is what you see when you scroll backwards:

<img width="1061" alt="Screen Shot 2021-05-19 at 1 50 16 PM" src="https://user-images.githubusercontent.com/13629122/118860362-4b76e900-b8a9-11eb-99c2-f355b5230b93.png">

**Comment by foltik** [comment]
Fixed for utterances with the same start and end time as of `SignStream3_3.7.0_pre_2021_05_25_1704_16f12c84` and `SignStream4_4.1.0_pre_2021_05_25_1708_694156a2`.

Note that the Cory collection has some utterances that are erroneously overlapping (U1 end > U2 start).
