### ISSUE TITLE
Zoom - Lock/Unlock: no difference

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#449]
With Lock selected in U1, I click on U2 and then again on U1, and the Zoom is different from what it had been in U1.
The behavior is identical if Unlocked is selected for the Zoom.

Same behavior if instead of clicking on U2, I went to Database View and Athen back to U1.

<img width="942" alt="Screen Shot 2021-05-14 at 1 44 13 PM" src="https://user-images.githubusercontent.com/13629122/118308934-92846900-b4ba-11eb-9b20-f0bd0ba9b34e.png">

<img width="871" alt="Screen Shot 2021-05-14 at 1 44 21 PM" src="https://user-images.githubusercontent.com/13629122/118308947-96b08680-b4ba-11eb-999f-89507ad7b24d.png">

<img width="870" alt="Screen Shot 2021-05-14 at 1 44 28 PM" src="https://user-images.githubusercontent.com/13629122/118309015-aa5bed00-b4ba-11eb-8d2a-d84f223e4b8d.png">

**Comment by foltik** [comment]
Fixed as of `SignStream4_4.1.0_pre_2021_05_14_1715_39304367` and `SignStream3_3.7.0_pre_2021_05_14_1713_f4fd6844`

**Comment by cneidle** [comment]
Still does not work in 3.7 

I look at U2 - Zoom is locked

<img width="1389" alt="Screen Shot 2021-05-14 at 9 07 42 PM" src="https://user-images.githubusercontent.com/13629122/118343742-a77fed00-b4f8-11eb-9877-3afb4823b7c6.png">

I don't touch the zoom bar.  Go to database view.

<img width="655" alt="Screen Shot 2021-05-14 at 9 07 50 PM" src="https://user-images.githubusercontent.com/13629122/118343744-ac44a100-b4f8-11eb-955d-b6029bd6cdfe.png">

Go back to U2.

<img width="914" alt="Screen Shot 2021-05-14 at 9 07 59 PM" src="https://user-images.githubusercontent.com/13629122/118343747-b070be80-b4f8-11eb-9723-cefe97a4f9c4.png">

**Comment by foltik** [comment]
@cneidle The current behavior is that when clicking on an utterance directly from the database view, all saved state (like open segment tiers, zoom) is discarded to show that single utterance, regardless of lock. The zoom lock only affects clicking between utterances via the index.

I think the idea was that you would use "Back to Database View" if you wanted to go back to what you were working on before, and click an utterance directly to start anew.

Would you prefer that clicking an utterance directly remembers the previous zoom if locked?

**Comment by cneidle** [comment]
> Would you prefer that clicking an utterance directly remembers the previous zoom if locked?

Yes.


But the Zoom does not appear to be working properly,
in other respects, as reported in a couple of recent reports 
on Github.

In particular, I hope you looked at the screen recording I sent.


Thank you.

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream3_3.7.0_pre_2021_05_19_1003_86750a7c
fixed
