### ISSUE TITLE
Problem with Zoom and Screen focus

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#454]
Please see the video I just sent by email - displaying the problem.  I also included the video I was working with.
Something is definitely not working properly with the RIT video P01_V01.

The utterance view shows the utterance as microscopic in length when going to the utterance view from the database view.

And the magnification of the DB view gets screwed up when switching to utterance view and back again.

The zoom ends up showing very little of the selected object and it takes multiple efforts to try to get to a point where you can see what you are doing to annotate.  It would be incredibly frustrating to try to annotate this video.

**Comment by foltik** [comment]
Fixed as of `SignStream3_3.7.0_pre_2021_05_19_1003_86750a7c`. Per email, please remove any collections saved while experiencing this issue.

**Comment by cneidle** [comment]
Mac OS 11.4.  May 26

There is something still not right about Zoom and Focus.  If the current frame is at the end of the sign shown below, and I increase the Zoom, look what happens.

<img width="1439" alt="Screen Shot 2021-05-26 at 1 30 37 PM" src="https://user-images.githubusercontent.com/13629122/119705738-1b8a9100-be27-11eb-9c13-15399e40c0d7.png">

<img width="1450" alt="Screen Shot 2021-05-26 at 1 30 49 PM" src="https://user-images.githubusercontent.com/13629122/119705749-204f4500-be27-11eb-8d2e-e72edfdf47f8.png">

**Comment by cneidle** [comment]
Compare with what happens in 3.3.5, which is what should happen:

<img width="804" alt="Screen Shot 2021-05-26 at 1 38 11 PM" src="https://user-images.githubusercontent.com/13629122/119706309-d155df80-be27-11eb-9aeb-6a8dba3c0898.png">

<img width="1320" alt="Screen Shot 2021-05-26 at 1 38 19 PM" src="https://user-images.githubusercontent.com/13629122/119706325-d61a9380-be27-11eb-894e-dd986a2a61a1.png">

**Comment by cneidle** [comment]
A related weirdness:  If I start out with things as in the top screen shot; I slide the zoom to zoom out, and then I slide the zoom back to the original position, I do not end up with the original view.

<img width="897" alt="Screen Shot 2021-05-26 at 1 41 42 PM" src="https://user-images.githubusercontent.com/13629122/119706730-57722600-be28-11eb-8c87-5d5640856f93.png">

<img width="988" alt="Screen Shot 2021-05-26 at 1 41 52 PM" src="https://user-images.githubusercontent.com/13629122/119706741-5a6d1680-be28-11eb-9d32-e32718970fef.png">

<img width="982" alt="Screen Shot 2021-05-26 at 1 42 00 PM" src="https://user-images.githubusercontent.com/13629122/119706746-5ccf7080-be28-11eb-97d9-6c523fb0fcfe.png">

**Comment by foltik** [comment]
> A related weirdness: If I start out with things as in the top screen shot; I slide the zoom to zoom out, and then I slide the zoom back to the original position, I do not end up with the original view.

While zooming, the position of the green bar is held constant. The position of the green bar changes when you zoom all the way out, so the original view can't be preserved while keeping the green bar in the same place. 

As long as there's still sufficient room on the screen for the green bar to remain in the same place, the view will be preserved.

(This is how zoom almost universally works; try zooming in and out on this webpage)

**Comment by foltik** [comment]
> There is something still not right about Zoom and Focus. If the current frame is at the end of the sign shown below, and I increase the Zoom, look what happens.

> Compare with what happens in 3.3.5, which is what should happen:

What's the difference in the 3.3.5 screenshot? It looks to me like in both cases the view is expanding around the sign, keeping the green bar in the same position relative to the sign. What are you expecting to happen?

**CAROL's REPLY:  The Zoom moves the selected item partially out of view.  In 3.3.5, the Zoom prioritizes keeping the Utterance in view.  You do not lose visibility of that gloss.**

**Comment by cneidle** [comment]
Why does zooming work differently from how it worked in 3.3.5, which is how it should work for annotation ?  Can we not use the same algorithm ??   If you do nothing other than slide the zoom level back and forth, ending in the original position, the view should be unchanged.

**Comment by foltik** [comment]
The algorithm is the same. The view is always preserved, unless you zoom **all the way out** and the green bar moves.

**Comment by cneidle** [comment]
Could you perhaps consult with Greg?  This is definitely not behaving the same...

**Comment by cneidle** [comment]
This is fundamentally different from the typical use of Zoom.

The typical use of Zoom is to focus in on a selected element

Here the Zoom bar serves to change the scale of the display — not necessarily
to focus in on any one element.  This is the only way we have to do this.

So if you’re viewing an utterance, changing the Zoom while the current
frame is near the edge of the utterance  should not display empty space outside 
the utterance preferentially to showing more of the utterance.

This works exactly the way it should in 3.3.5

(The only problem with the Zoom there is with the 30 fps movies,
but that’s a different issue.)

**Comment by cneidle** [comment]
OS 10.12.6 - version Doug sent on Thursday, May 27 

What you said about the Zoom is not true.   I start with the view in 1 below.   I move the zoom to the level shown in 2, do nothing else (i.e., the green bar does not move) and then move the zoom back to the original level.  The display has changed, as shown in 3.

<img width="1087" alt="Screen Shot 2021-05-27 at 10 05 50 AM" src="https://user-images.githubusercontent.com/13629122/119841478-d40e0e80-bed3-11eb-9659-ad23288c3486.png">


<img width="1092" alt="Screen Shot 2021-05-27 at 10 06 03 AM" src="https://user-images.githubusercontent.com/13629122/119841511-da03ef80-bed3-11eb-8892-5ba35e687683.png">


<img width="1088" alt="Screen Shot 2021-05-27 at 10 07 07 AM" src="https://user-images.githubusercontent.com/13629122/119841524-dec8a380-bed3-11eb-8a30-fdd2ef0a4108.png">

**Comment by foltik** [comment]
> I start with the view in 1 below. I move the zoom to the level shown in 2, do nothing else (i.e., the green bar does not move)

When you zoomed out, the scrollbar hit the beginning of the video. This changes the relative horizontal position of the green bar on the screen. When this happens, the view will be in a different spot when you zoom back in.

**Comment by douglas-motto-at-rutgers** [comment]
Carol,

We see the zoom working exactly as it is in 3.3.1 and 3.3.5.

I am closing this issue.

If a change is desired, please open a new feature request issue.
